### ISSUE TITLE
What'sapp .exe location error

### ISSUE THREAD

**Issue by AshishRamesh** [jaspreetsidhu3/voice_assistant#1]
Hi,
The code right now looks for the exe file in a specific folder which causes a file not found error.

**Comment by jaspreetsidhu3** [comment]
Hi Ashish,
You can simply comment or remove these lines of code from amigo.py
```
 elif 'open whatsapp' in query:
            speak("opening whatsapp")
            loc = "C:\\Users\\jaspr\\AppData\\Local\\WhatsApp\\WhatsApp.exe"
            os.startfile(loc)
```
The code above is only for the demonstration to run any executable program.
Thanks,
Jaspreet
